sudo: false
os: linux
dist: trusty
language: cpp
compiler:
- gcc
env:
  global:
  - CCACHE_SIZE=100M
  - CCACHE_TEMPDIR=/tmp/.ccache-temp
  - CCACHE_COMPRESS=1
  - STORAGE_DEST=gs://$BUCKET/$PROJECT/$TRAVIS_BRANCH/
cache:
  apt: true
  directories:
  - depends/built
  - depends/sdk-sources
  - "$HOME/google-cloud-sdk/"
  - "$HOME/.ccache"
matrix:
  fast_finish: true
  include:
  - compiler: ": Linux"
    env: BUILD_SCRIPT=build.sh
      PACKAGES="build-essential pkg-config libc6-dev m4 g++-multilib
      autoconf libtool ncurses-dev unzip python zlib1g-dev wget bsdmainutils automake
      libssl-dev libprotobuf-dev protobuf-compiler libqrencode-dev libdb++-dev software-properties-common
      libcurl4-openssl-dev curl"
      PACKAGE_NAME=verus-cli-linux.tar.gz
      PACKAGING_MATRIX="cp src/komodod src/komodo-cli kmd/linux/verus-cli && chmod +x kmd/linux/verus-cli/komodod && chmod +x kmd/linux/verus-cli/komodo-cli && cd kmd/linux && tar -czf $PACKAGE_NAME verus-cli && ls"
  - compiler: ": Windows"
    env: RUST_TARGET=x86_64-pc-windows-gnu
      BUILD_SCRIPT=build-win.sh
      PACKAGES="build-essential pkg-config libcurl3-gnutls-dev
      libc6-dev libevent-dev m4 g++-multilib autoconf libtool ncurses-dev unzip git
      python zlib1g-dev wget bsdmainutils automake libssl-dev libprotobuf-dev protobuf-compiler
      libdb++-dev ntp ntpdate mingw-w64 wine bc"
      PACKAGE_NAME=verus-cli-windows.zip
      PACKAGING_MATRIX="cp src/komodod.exe src/komodo-cli.exe src/komodo-tx.exe kmd/windows/verus-cli &&
      cd kmd/windows && zip -r9 $PACKAGE_NAME verus-cli && ls"
  exclude:
  - compiler: gcc
install:
- rm -f /etc/apt/sources.list.d/travis_ci_zeromq3-source.list
- travis_retry apt-get -y update && travis_retry apt-get -y install -qq $PACKAGES
- if [ -n "$RUST_TARGET" ]; then curl -sSf https://build.travis-ci.org/files/rustup-init.sh
  | sh -s -- --default-toolchain stable -y && export PATH=$PATH:$HOME/.cargo/bin:$PATH && rustup target add $RUST_TARGET; fi
before_script:
- unset CC; unset CXX
script:
- "./zcutil/$BUILD_SCRIPT -j2"
