sudo: required
os: linux
dist: xenial
language: cpp
compiler:
- gcc
env:
  global:
  - SDK_URL=https://bitcoincore.org/depends-sources/sdks
  - KOMODO_BUILD_DIR=Komodo-build
  - COMPRESSED_BUILD=Komodo-build.tar.gz
  - CCACHE_SIZE=100M
  - CCACHE_TEMPDIR=/tmp/.ccache-temp
  - CCACHE_COMPRESS=1
cache:
  apt: true
  directories:
  - depends/built
  - depends/sdk-sources
  - "$HOME/google-cloud-sdk/"
  - "$HOME/.ccache"
matrix:
  fast_finish: true
  include:

  - compiler: ": Mac"
    os: osx
    osx_image: xcode9.2
    env: 'HOST=x86_64-apple-darwin11 TARGET=x86_64-apple-darwin BUILD_SCRIPT=build-mac.sh
      TRAVIS_OS_NAME=osx PACKAGES="binutils protobuf autogen" OSX_SDK=10.9
  exclude:
  - compiler: gcc
install:
- if [ $TARGET_PLATFORM = Win64 ]; then curl -sSf https://build.travis-ci.org/files/rustup-init.sh
  | sh -s -- --default-toolchain stable -y && export PATH=$PATH:$HOME/.cargo/bin:$PATH;
  fi
- if [ $TARGET_PLATFORM = Win64 ]; then rustup target add $RUST_TARGET; fi
- if [ $TRAVIS_OS_NAME = osx ]; then brew upgrade python coreutils automake; fi
- if [ $TRAVIS_OS_NAME = osx ]; then travis_retry brew tap discoteq/discoteq && brew
  install flock; fi
- if [ $TRAVIS_OS_NAME = osx ]; then rm '/usr/local/include/c++' && travis_retry brew
  tap homebrew/homebrew-core && brew install homebrew/homebrew-core/gcc@5 --overwrite
  gcc@5; fi
- if [ $TRAVIS_OS_NAME = osx ]; then travis_retry brew update && brew install $PACKAGES;
  fi
before_script:
- unset CC; unset CXX
- mkdir -p depends/SDKs depends/sdk-sources
script:
- "./zcutil/fetch-params.sh"
- "./zcutil/$BUILD_SCRIPT -j2"
after_script:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then gcloud auth activate-service-account
  --key-file AUTH_KEY.json; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then gsutil cp gs://$BUCKET/CI-TESTS/$PROJECT/$TRAVIS_BRANCH/$TARGET_PLATFORM.tar.gz
  . && tar -xzvf $TARGET_PLATFORM.tar.gz && ls && rm $TARGET_PLATFORM.tar.gz; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then cp -rv $KOMODO_EXEC_SET $TARGET_PLATFORM
  && cd src && tar -czvf $TARGET_PLATFORM.tar.gz $TARGET_PLATFORM; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then gsutil cp -rv $TARGET_PLATFORM.tar.gz
  gs://$BUCKET/CI-TESTS/$PROJECT/$TRAVIS_BRANCH/; fi

